  development:
    adapter: mysql2
    encoding: utf8mb4
    reconnect: false
    database: lobsters
    socket: /run/mysqld/mysqld.sock
    username: lobsters
    password: lobsters

  production:
    adapter: mysql2
    encoding: utf8mb4
    reconnect: false
    database: lobsters
    socket: /run/mysqld/mysqld.sock
    username: lobsters
    password: lobsters
    pool: 5

  test:
    adapter: sqlite3
    database: db/test.sqlite3
    pool: 5
    timeout: 5000
